[it]
  languageCode = 'it-IT'
  languageName = 'Italiano'
  title = 'Antonio Toto Castaldi'
  weight = 1

[en]
  languageCode = 'en-US'
  languageName = 'English'
  title = 'Antonio Toto Castaldi'
  weight = 2
